name: First PR

on: 
  pull_request_target:
    types: 
      - opened

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Step1
        uses: actions/first-interaction@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Welcome onboard!
